"use client";

import { error } from 'console';
import { useState, useEffect } from 'react';

export default function Dashboard() {
  // React State Hooks: Think of these as variables that automatically
  // redraw the webpage whenever their contents update.
  const [file, setFile] = useState<File | null>(null);
  const [category, setCategory] = useState('tech');
  const [uploadStatus, setUploadStatus] = useState('');

  // Form handler for file submission to our Next.js API
  const handleUploadSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!file) return;

    setUploadStatus('Uploading...');
    
    // Package file parameters into standard browser FormData payload
    const formData = new FormData();
    formData.append('file', file);
    formData.append('category', category);

    // Send HTTP POST request directly to our backend API route
    const res = await fetch('/api/upload', {
      method: 'POST',
      body: formData,
    });

    const data = await res.json();
    if (data.success) {
      setUploadStatus(`Success: ${data.message}`);
    } else {
      setUploadStatus(`Error: ${data.error}`);
    }
  };

  return (
    <main style={{ padding: '40px', fontFamily: 'sans-serif', maxWidth: '900px', margin: '0 auto' }}>
      <h1>Auto-CV Automation Control Center</h1>
      <p style={{ color: '#666' }}>Layer 2 Database & Profile Management System</p>

      {/* SECTION 1: RESUME PROFILE MANAGER */}
      <section style={{ border: '1px solid #ccc', padding: '20px', borderRadius: '8px', marginBottom: '30px' }}>
        <h2>1. Knowledge Base Asset Manager</h2>
        <form onSubmit={handleUploadSubmit}>
          <div style={{ marginBottom: '15px' }}>
            <label style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold' }}>Select Profile Category:</label>
            <select value={category} onChange={(e) => setCategory(e.target.value)} style={{ padding: '8px', width: '200px' }}>
              <option value="tech">Software Development (Tech)</option>
              <option value="robotics">Robotics & AI (Hardware/Control)</option>
              <option value="education">Academic / Education</option>
            </select>
          </div>

          <div style={{ marginBottom: '15px' }}>
            <label style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold' }}>Upload Markdown (.md) File:</label>
            <input 
              type="file" 
              accept=".md" 
              onChange={(e: React.ChangeEvent<HTMLInputElement>) => setFile(e.target.files ? e.target.files[0] : null)} 
              style={{ padding: '5px' }}
            />
          </div>

          <button type="submit" style={{ padding: '10px 20px', background: '#0070f3', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>
            Upload Master Template
          </button>
        </form>
        {uploadStatus && <p style={{ marginTop: '10px', fontWeight: 'bold', color: '#0070f3' }}>{uploadStatus}</p>}
      </section>

      {/* SECTION 2: APPLICATION TRACKER GRID HOLDER */}
      <section style={{ border: '1px solid #ccc', padding: '20px', borderRadius: '8px' }}>
        <h2>2. Live Vacancy Application Queue</h2>
        <p style={{ fontSize: '14px', color: '#666' }}>This table displays jobs generated by Layer 1's Python scraping routines from your local SQLite instance.</p>
        
        {/* Placeholder table - when we link our jobs API route later, this maps out live rows */}
        <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: '15px' }}>
          <thead>
            <tr style={{ background: '#f5f5f5', textAlign: 'left' }}>
              <th style={{ padding: '10px', borderBottom: '2px solid #ddd' }}>Company</th>
              <th style={{ padding: '10px', borderBottom: '2px solid #ddd' }}>Position</th>
              <th style={{ padding: '10px', borderBottom: '2px solid #ddd' }}>Salary</th>
              <th style={{ padding: '10px', borderBottom: '2px solid #ddd' }}>HR Contact</th>
              <th style={{ padding: '10px', borderBottom: '2px solid #ddd' }}>Status</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style={{ padding: '10px', borderBottom: '1px solid #eee' }} colSpan={5}>
                Ready to link. Running your python scraper will pipe jobs straight into this interface view container.
              </td>
            </tr>
          </tbody>
        </table>
      </section>
    </main>
  );
}